### ISSUE TITLE
Remove hard-coded point values

### ISSUE THREAD

**Issue by TwelveNights** [UBCMJC/MJCApp#16]
We can modify the code to use the default formula to calculate points.

fu \* 2^(2+han) is the equation.
e.g.
30 fu, 4 han would be
30 \* 2^6 = 1920.
Basic points would be 1920.
If the non-dealer deals into the dealer, they pay 1920x6 rounded up = 11600
If someone deals into a non-dealer, they pay 1920x4 rounded up = 7700
If the dealer self-draws, all players pay 1920x2 = 3900
If the non-dealer wins by self-draw, the dealer pays 3900, and non-dealers pay 2000.

**Comment by 0spooky** [comment]
Split into issues #65 and #66
