### ISSUE TITLE
Autodeselect winner/loser buttons and # of dora

### ISSUE THREAD

**Issue by whalewatchers** [UBCMJC/MJCApp#2]

**Comment by TwelveNights** [comment]
I'll take this task.

**Comment by TwelveNights** [comment]
Ready for review @Futochu. Opened #9.

**Comment by Futochu** [comment]
Please fix your PR

**Comment by TwelveNights** [comment]
I'll get it done soon(tm). I just have to look through the conflict markers, in case I accidentally miss something.

**Comment by TwelveNights** [comment]
Closed as of #9 and #40
