### ISSUE TITLE
Last hand can be deleted when no hands are submitted

### ISSUE THREAD

**Issue by TwelveNights** [UBCMJC/MJCApp#7]
The button should probaby be disabled when there are no hands in the current game. Also, an error message pops up on the console while trying to delete hands:

`Uncaught TypeError: Cannot read property 'eastDelta' of undefined`

**Comment by Futochu** [comment]
I'm aware of this but it does not break functionalities and is invisible to users.  It's pretty easy to fix though

**Comment by TwelveNights** [comment]
This is only for hk it seems.

**Comment by TwelveNights** [comment]
Managed to create a fix on #12. Ready for review @Futochu.
